# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\S\VSCforPython\.vscode\Zhuyi\BeginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(903, 597)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.begin_focus = QtWidgets.QPushButton(self.centralwidget)
        self.begin_focus.setGeometry(QtCore.QRect(240, 80, 400, 400))
        font = QtGui.QFont()
        font.setPointSize(34)
        font.setBold(True)
        font.setWeight(75)
        self.begin_focus.setFont(font)
        self.begin_focus.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius:200px;\n"
"border:20px solid rgb(171, 202, 125);\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.begin_focus.setObjectName("begin_focus")
        self.chicken_soup = QtWidgets.QLabel(self.centralwidget)
        self.chicken_soup.setGeometry(QtCore.QRect(130, 510, 401, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.chicken_soup.setFont(font)
        self.chicken_soup.setObjectName("chicken_soup")
        self.date_display = QtWidgets.QLabel(self.centralwidget)
        self.date_display.setGeometry(QtCore.QRect(760, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.date_display.setFont(font)
        self.date_display.setObjectName("date_display")
        self.week_display = QtWidgets.QLabel(self.centralwidget)
        self.week_display.setGeometry(QtCore.QRect(760, 50, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.week_display.setFont(font)
        self.week_display.setObjectName("week_display")
        self.time_display = QtWidgets.QLabel(self.centralwidget)
        self.time_display.setGeometry(QtCore.QRect(760, 90, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.time_display.setFont(font)
        self.time_display.setObjectName("time_display")
        self.focus_history = QtWidgets.QPushButton(self.centralwidget)
        self.focus_history.setGeometry(QtCore.QRect(20, 100, 71, 71))
        self.focus_history.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/history2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.focus_history.setIcon(icon)
        self.focus_history.setIconSize(QtCore.QSize(60, 60))
        self.focus_history.setCheckable(False)
        self.focus_history.setAutoRepeat(False)
        self.focus_history.setAutoExclusive(False)
        self.focus_history.setAutoDefault(False)
        self.focus_history.setDefault(False)
        self.focus_history.setFlat(True)
        self.focus_history.setObjectName("focus_history")
        self.settings = QtWidgets.QPushButton(self.centralwidget)
        self.settings.setGeometry(QtCore.QRect(20, 20, 71, 71))
        self.settings.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings.setIcon(icon1)
        self.settings.setIconSize(QtCore.QSize(60, 60))
        self.settings.setFlat(True)
        self.settings.setObjectName("settings")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-30, -10, 941, 621))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setPixmap(QtGui.QPixmap(":/images/main_background.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.label.raise_()
        self.chicken_soup.raise_()
        self.date_display.raise_()
        self.week_display.raise_()
        self.time_display.raise_()
        self.focus_history.raise_()
        self.settings.raise_()
        self.begin_focus.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "铸意"))
        self.begin_focus.setText(_translate("MainWindow", "开始专注"))
        self.chicken_soup.setText(_translate("MainWindow", "chicken soup here"))
        self.date_display.setText(_translate("MainWindow", "date here"))
        self.week_display.setText(_translate("MainWindow", "week here"))
        self.time_display.setText(_translate("MainWindow", "time here"))
import resource_rc
