# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\S\VSCforPython\.vscode\Zhuyi\Focus.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_focus(object):
    def setupUi(self, focus):
        focus.setObjectName("focus")
        focus.resize(369, 212)
        self.focus_time = QtWidgets.QLabel(focus)
        self.focus_time.setGeometry(QtCore.QRect(60, 50, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.focus_time.setFont(font)
        self.focus_time.setObjectName("focus_time")
        self.end_focus = QtWidgets.QPushButton(focus)
        self.end_focus.setGeometry(QtCore.QRect(80, 120, 121, 31))
        self.end_focus.setObjectName("end_focus")

        self.retranslateUi(focus)
        QtCore.QMetaObject.connectSlotsByName(focus)

    def retranslateUi(self, focus):
        _translate = QtCore.QCoreApplication.translate
        focus.setWindowTitle(_translate("focus", "Dialog"))
        self.focus_time.setText(_translate("focus", "fucus time here"))
        self.end_focus.setText(_translate("focus", "结束专注"))
