# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\S\VSCforPython\.vscode\Zhuyi\History.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_history(object):
    def setupUi(self, history):
        history.setObjectName("history")
        history.resize(659, 487)
        self.history_list = QtWidgets.QListWidget(history)
        self.history_list.setGeometry(QtCore.QRect(10, 20, 631, 331))
        self.history_list.setObjectName("history_list")
        self.del_history = QtWidgets.QPushButton(history)
        self.del_history.setGeometry(QtCore.QRect(260, 400, 141, 41))
        self.del_history.setObjectName("del_history")

        self.retranslateUi(history)
        QtCore.QMetaObject.connectSlotsByName(history)

    def retranslateUi(self, history):
        _translate = QtCore.QCoreApplication.translate
        history.setWindowTitle(_translate("history", "Dialog"))
        self.del_history.setText(_translate("history", "del"))
