# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\S\VSCforPython\.vscode\Zhuyi\Report.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_report(object):
    def setupUi(self, report):
        report.setObjectName("report")
        report.resize(753, 564)
        self.label = QtWidgets.QLabel(report)
        self.label.setGeometry(QtCore.QRect(230, 60, 151, 31))
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(report)
        self.formLayoutWidget.setGeometry(QtCore.QRect(180, 150, 321, 281))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.focus_time = QtWidgets.QLabel(self.formLayoutWidget)
        self.focus_time.setObjectName("focus_time")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.focus_time)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.eye_det_fail_per = QtWidgets.QLabel(self.formLayoutWidget)
        self.eye_det_fail_per.setObjectName("eye_det_fail_per")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.eye_det_fail_per)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.proc_det_fail_time = QtWidgets.QLabel(self.formLayoutWidget)
        self.proc_det_fail_time.setObjectName("proc_det_fail_time")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.proc_det_fail_time)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.score = QtWidgets.QLabel(self.formLayoutWidget)
        self.score.setObjectName("score")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.score)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.eye_det_fail_time = QtWidgets.QLabel(self.formLayoutWidget)
        self.eye_det_fail_time.setObjectName("eye_det_fail_time")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.eye_det_fail_time)

        self.retranslateUi(report)
        QtCore.QMetaObject.connectSlotsByName(report)

    def retranslateUi(self, report):
        _translate = QtCore.QCoreApplication.translate
        report.setWindowTitle(_translate("report", "Dialog"))
        self.label.setText(_translate("report", "专注报告"))
        self.label_2.setText(_translate("report", "专注时常："))
        self.focus_time.setText(_translate("report", "TextLabel"))
        self.label_4.setText(_translate("report", "未检测到眼睛时常："))
        self.eye_det_fail_per.setText(_translate("report", "TextLabel"))
        self.label_6.setText(_translate("report", "黑名单应用开启次数："))
        self.proc_det_fail_time.setText(_translate("report", "TextLabel"))
        self.label_8.setText(_translate("report", "得分："))
        self.score.setText(_translate("report", "TextLabel"))
        self.label_3.setText(_translate("report", "未检测到眼睛次数："))
        self.eye_det_fail_time.setText(_translate("report", "TextLabel"))
