# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\S\VSCforPython\.vscode\Zhuyi\Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settings(object):
    def setupUi(self, settings):
        settings.setObjectName("settings")
        settings.resize(729, 443)
        self.add_proc = QtWidgets.QPushButton(settings)
        self.add_proc.setGeometry(QtCore.QRect(420, 100, 121, 41))
        self.add_proc.setObjectName("add_proc")
        self.new_proc = QtWidgets.QLineEdit(settings)
        self.new_proc.setGeometry(QtCore.QRect(130, 100, 281, 41))
        self.new_proc.setObjectName("new_proc")
        self.now_proc = QtWidgets.QListWidget(settings)
        self.now_proc.setGeometry(QtCore.QRect(130, 160, 411, 221))
        self.now_proc.setObjectName("now_proc")
        self.save = QtWidgets.QPushButton(settings)
        self.save.setGeometry(QtCore.QRect(590, 270, 101, 91))
        self.save.setObjectName("save")

        self.retranslateUi(settings)
        QtCore.QMetaObject.connectSlotsByName(settings)

    def retranslateUi(self, settings):
        _translate = QtCore.QCoreApplication.translate
        settings.setWindowTitle(_translate("settings", "设置"))
        self.add_proc.setText(_translate("settings", "add"))
        self.save.setText(_translate("settings", "Save"))
